// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package savonitar.click2win.protobuf;

public interface ServerGameEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServerGameEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 targetX = 1;</code>
   */
  int getTargetX();

  /**
   * <code>int32 targetY = 2;</code>
   */
  int getTargetY();

  /**
   * <code>int32 score = 3;</code>
   */
  int getScore();

  /**
   * <code>bool end = 4;</code>
   */
  boolean getEnd();
}
