// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package savonitar.click2win.gameserver.protobuf;

public final class GameServiceProto {
  private GameServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerGameEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerGameEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerClickedEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerClickedEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tapi.proto\"&\n\014StartRequest\022\026\n\016requestMe" +
      "ssage\030\001 \001(\t\"(\n\rStartResponse\022\027\n\017response" +
      "Message\030\001 \001(\t\"O\n\017ServerGameEvent\022\017\n\007targ" +
      "etX\030\001 \001(\005\022\017\n\007targetY\030\002 \001(\005\022\r\n\005score\030\003 \001(" +
      "\005\022\013\n\003end\030\004 \001(\010\"&\n\013PlayerEvent\022\027\n\017respons" +
      "eMessage\030\001 \001(\t\"*\n\022PlayerClickedEvent\022\t\n\001" +
      "x\030\001 \001(\005\022\t\n\001y\030\002 \001(\0052N\n\022GameSessionService" +
      "\0228\n\013GameSession\022\023.PlayerClickedEvent\032\020.S" +
      "erverGameEvent(\0010\001B2\n\034savonitar.click2wi" +
      "n.protobufB\020GameServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_StartRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StartRequest_descriptor,
        new String[] { "RequestMessage", });
    internal_static_StartResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_StartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StartResponse_descriptor,
        new String[] { "ResponseMessage", });
    internal_static_ServerGameEvent_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ServerGameEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerGameEvent_descriptor,
        new String[] { "TargetX", "TargetY", "Score", "End", });
    internal_static_PlayerEvent_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PlayerEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerEvent_descriptor,
        new String[] { "ResponseMessage", });
    internal_static_PlayerClickedEvent_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PlayerClickedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerClickedEvent_descriptor,
        new String[] { "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
