// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package savonitar.click2win.gameserver.protobuf;

public interface PlayerClickedEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PlayerClickedEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 x = 1;</code>
   */
  int getX();

  /**
   * <code>int32 y = 2;</code>
   */
  int getY();
}
