// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package savonitar.click2win.gameserver.protobuf;

public interface StartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestMessage = 1;</code>
   */
  String getRequestMessage();
  /**
   * <code>string requestMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestMessageBytes();
}
