openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /api/gamesession/start:
    post:
      tags:
        - game-session-controller
      operationId: startSession
      parameters:
        - name: player
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/gamesession/click:
    post:
      tags:
        - game-session-controller
      operationId: playerClick
      parameters:
        - name: session
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayerClickedEvent'
        required: true
      responses:
        "200":
          description: OK
  /api/player/top:
    get:
      tags:
        - player-controller
      operationId: getTopPlayers
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
  /api/player/rating:
    get:
      tags:
        - player-controller
      operationId: playerRating
      parameters:
        - name: playerName
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: integer
                format: int32
  /api/player/count:
    get:
      tags:
        - player-controller
      operationId: countPlayers
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: integer
                format: int64
  /api/gamesession/next:
    get:
      tags:
        - game-session-controller
      operationId: nextTarget
      parameters:
        - name: session
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ServerGameEvent'
components:
  schemas:
    PlayerClickedEvent:
      type: object
      properties:
        x:
          type: integer
          format: int32
        "y":
          type: integer
          format: int32
    Player:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        playerName:
          type: string
        rating:
          type: integer
          format: int32
    ServerGameEvent:
      type: object
      properties:
        x:
          type: integer
          format: int32
        "y":
          type: integer
          format: int32
        end:
          type: boolean
        score:
          type: integer
          format: int32
