// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package savonitar.click2win.protobuf;

public interface PlayerEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PlayerEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   */
  String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
