// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package savonitar.click2win.protobuf;

/**
 * Protobuf type {@code ServerGameEvent}
 */
public  final class ServerGameEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ServerGameEvent)
        ServerGameEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServerGameEvent.newBuilder() to construct.
  private ServerGameEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServerGameEvent() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ServerGameEvent(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            targetX_ = input.readInt32();
            break;
          }
          case 16: {

            targetY_ = input.readInt32();
            break;
          }
          case 24: {

            score_ = input.readInt32();
            break;
          }
          case 32: {

            end_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GameServiceProto.internal_static_ServerGameEvent_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GameServiceProto.internal_static_ServerGameEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ServerGameEvent.class, ServerGameEvent.Builder.class);
  }

  public static final int TARGETX_FIELD_NUMBER = 1;
  private int targetX_;
  /**
   * <code>int32 targetX = 1;</code>
   */
  public int getTargetX() {
    return targetX_;
  }

  public static final int TARGETY_FIELD_NUMBER = 2;
  private int targetY_;
  /**
   * <code>int32 targetY = 2;</code>
   */
  public int getTargetY() {
    return targetY_;
  }

  public static final int SCORE_FIELD_NUMBER = 3;
  private int score_;
  /**
   * <code>int32 score = 3;</code>
   */
  public int getScore() {
    return score_;
  }

  public static final int END_FIELD_NUMBER = 4;
  private boolean end_;
  /**
   * <code>bool end = 4;</code>
   */
  public boolean getEnd() {
    return end_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (targetX_ != 0) {
      output.writeInt32(1, targetX_);
    }
    if (targetY_ != 0) {
      output.writeInt32(2, targetY_);
    }
    if (score_ != 0) {
      output.writeInt32(3, score_);
    }
    if (end_ != false) {
      output.writeBool(4, end_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (targetX_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, targetX_);
    }
    if (targetY_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, targetY_);
    }
    if (score_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, score_);
    }
    if (end_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, end_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ServerGameEvent)) {
      return super.equals(obj);
    }
    ServerGameEvent other = (ServerGameEvent) obj;

    if (getTargetX()
        != other.getTargetX()) return false;
    if (getTargetY()
        != other.getTargetY()) return false;
    if (getScore()
        != other.getScore()) return false;
    if (getEnd()
        != other.getEnd()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TARGETX_FIELD_NUMBER;
    hash = (53 * hash) + getTargetX();
    hash = (37 * hash) + TARGETY_FIELD_NUMBER;
    hash = (53 * hash) + getTargetY();
    hash = (37 * hash) + SCORE_FIELD_NUMBER;
    hash = (53 * hash) + getScore();
    hash = (37 * hash) + END_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEnd());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ServerGameEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ServerGameEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ServerGameEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ServerGameEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ServerGameEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ServerGameEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ServerGameEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ServerGameEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ServerGameEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ServerGameEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ServerGameEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ServerGameEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ServerGameEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ServerGameEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ServerGameEvent)
          ServerGameEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GameServiceProto.internal_static_ServerGameEvent_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GameServiceProto.internal_static_ServerGameEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ServerGameEvent.class, ServerGameEvent.Builder.class);
    }

    // Construct using savonitar.click2win.protobuf.ServerGameEvent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      targetX_ = 0;

      targetY_ = 0;

      score_ = 0;

      end_ = false;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GameServiceProto.internal_static_ServerGameEvent_descriptor;
    }

    @Override
    public ServerGameEvent getDefaultInstanceForType() {
      return ServerGameEvent.getDefaultInstance();
    }

    @Override
    public ServerGameEvent build() {
      ServerGameEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ServerGameEvent buildPartial() {
      ServerGameEvent result = new ServerGameEvent(this);
      result.targetX_ = targetX_;
      result.targetY_ = targetY_;
      result.score_ = score_;
      result.end_ = end_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ServerGameEvent) {
        return mergeFrom((ServerGameEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ServerGameEvent other) {
      if (other == ServerGameEvent.getDefaultInstance()) return this;
      if (other.getTargetX() != 0) {
        setTargetX(other.getTargetX());
      }
      if (other.getTargetY() != 0) {
        setTargetY(other.getTargetY());
      }
      if (other.getScore() != 0) {
        setScore(other.getScore());
      }
      if (other.getEnd() != false) {
        setEnd(other.getEnd());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ServerGameEvent parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ServerGameEvent) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int targetX_ ;
    /**
     * <code>int32 targetX = 1;</code>
     */
    public int getTargetX() {
      return targetX_;
    }
    /**
     * <code>int32 targetX = 1;</code>
     */
    public Builder setTargetX(int value) {
      
      targetX_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 targetX = 1;</code>
     */
    public Builder clearTargetX() {
      
      targetX_ = 0;
      onChanged();
      return this;
    }

    private int targetY_ ;
    /**
     * <code>int32 targetY = 2;</code>
     */
    public int getTargetY() {
      return targetY_;
    }
    /**
     * <code>int32 targetY = 2;</code>
     */
    public Builder setTargetY(int value) {
      
      targetY_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 targetY = 2;</code>
     */
    public Builder clearTargetY() {
      
      targetY_ = 0;
      onChanged();
      return this;
    }

    private int score_ ;
    /**
     * <code>int32 score = 3;</code>
     */
    public int getScore() {
      return score_;
    }
    /**
     * <code>int32 score = 3;</code>
     */
    public Builder setScore(int value) {
      
      score_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 score = 3;</code>
     */
    public Builder clearScore() {
      
      score_ = 0;
      onChanged();
      return this;
    }

    private boolean end_ ;
    /**
     * <code>bool end = 4;</code>
     */
    public boolean getEnd() {
      return end_;
    }
    /**
     * <code>bool end = 4;</code>
     */
    public Builder setEnd(boolean value) {
      
      end_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool end = 4;</code>
     */
    public Builder clearEnd() {
      
      end_ = false;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ServerGameEvent)
  }

  // @@protoc_insertion_point(class_scope:ServerGameEvent)
  private static final ServerGameEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ServerGameEvent();
  }

  public static ServerGameEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerGameEvent>
      PARSER = new com.google.protobuf.AbstractParser<ServerGameEvent>() {
    @Override
    public ServerGameEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ServerGameEvent(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServerGameEvent> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ServerGameEvent> getParserForType() {
    return PARSER;
  }

  @Override
  public ServerGameEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

